on: [push]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Code Inspector Check
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@juli1/use-api-token
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_api_token: ${{ secrets.CODE_INSPECTOR_API_TOKEN }}
        min_quality_grade: 'WARNING'
        min_quality_score: '90'
        max_defects_rate: '0.2'
        max_complex_functions_rate: '0.0001'
        max_long_functions_rate: '0.0001'
        project_name: ''
        max_timeout_sec: '600'
        force_branch: 'master'
